package com.pingbits.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.pingbits.greendao.Ordder;

import com.pingbits.greendao.OrdderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ordderDaoConfig;

    private final OrdderDao ordderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ordderDaoConfig = daoConfigMap.get(OrdderDao.class).clone();
        ordderDaoConfig.initIdentityScope(type);

        ordderDao = new OrdderDao(ordderDaoConfig, this);

        registerDao(Ordder.class, ordderDao);
    }
    
    public void clear() {
        ordderDaoConfig.getIdentityScope().clear();
    }

    public OrdderDao getOrdderDao() {
        return ordderDao;
    }

}
